### PR TITLE
Fix Sentinel query logic with restart date

### PR DESCRIPTION
**Pull request by davidcordeiro-deimos**
Fixes #

### Proposed fixes:
Regarding Issue #106 the query logic using the restart date as been updated. The priority is now **restart_date** (previous job) --> **start_date** (harvest configuration) --> **'*'** (default) 

### Features:

- [ ] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [X] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by JGulic** [comment]
One note:
I was testing this version of the harvester, but then I switched to another branch which uses the harvester without these changes.
As a result, the harvester (the version without this change) on the first run (which is basically the only run for that version of the harvester if we have a defined time range) the harvester was able to collect one more dataset.
This version of the harvester skipped one in the first run.

In general, the harvester sometimes collects 99 and sometimes 100 datasets per run. This is the reason for the 1 dataset, that I was able to collect with the older version of the sentinel harvester.

**Comment by JGulic** [comment]
@davidcordeiro-deimos I am using the configuration with no. of datasets to collect set to a 100. And I have previously ran the harvester few times before switching to the old version branch for this.
My local harvester (running on this branch) has already collected more then 500 datasets, before I changed the branch. So the missing dataset should have been collected already.
Can you test this out again locally and see if you are going to see the same issue?

Also, set the   "datasets_per_job": 100 and check the jobs and the number of datasets that you collect per run.

**Comment by michellecbox** [comment]
@davidcordeiro-deimos could you look at this please?

**Comment by davidcordeiro-deimos** [comment]
I think I not understanding the issue that you are describing. 

The expected behavior for datasets_per_job = 100 is as follows:
- 1st job -> 100 new datasets collected
- 2nd and following jobs -> 99 new datasets collected and 1 updated (the same dataset as the last one collected from the previous job)

We chose this approach in order to make sure that we never skip any dataset. If this is not the behavior that you are reproducing, please let me know.

image

**Comment by JGulic** [comment]
@davidcordeiro-deimos I've tested this locally on a completely empty database. I never got to see that one dataset has been updated in the run. the UI only shows that 99 dataset have been collected and 0 for updated and deleted.

image

The gather queue is showing this in the logs:
`vde_20171231t234303 has not been harvested before. Creating a new harvest object.
2020-01-15 10:45:26,326 DEBUG [ckanext.nextgeossharvest.lib.opensearch_base] s3a_ol_2_lrr____20171230t195114_20171230t203514_20180101t000747_2640_026_142______ln1_o_nt_002 has not been harvested before. Creating a new harvest object.
2020-01-15 10:45:26,339 DEBUG [ckanext.harvest.queue] Received from plugin gather_stage: 100 objects (first: [u'f9821032-d930-454b-872a-aaedc1423974'] last: [u'9ee8e936-9839-41ec-9abc-093ad1deba0c'])
2020-01-15 10:45:26,356 DEBUG [ckanext.harvest.queue] Sent 100 objects to the fetch queue
`
But the fetch queue logs don't show anything about what happens to one dataset. I've tried debugging the _create_or_update_dataset but the update part never gets called.

Can you maybe compare the code that you have locally with the one that we have on this repo?

**Comment by davidcordeiro-deimos** [comment]
@JGulic I will look into this, I will let you know my feedback as soon as possible

**Comment by davidcordeiro-deimos** [comment]
@JGulic I have been analyzing this issue, and my conclusions are as follow:
- If `update_all` is set to false, then the behavior that you are experiencing is the correct one.
   * To be certain, you can check in the `gather` log if you have a message similar to `XXXX will not be updated.` for the repeated dataset.
   * On our side, the updated dataset was appearing due to a known discrepancy already discussed in PR #104 where the package metadata field `extras` is stored differently. Due to this, the [extend check](https://github.com/NextGeoss/ckanext-nextgeossharvest/blob/c0bb3a7dfe372fa2df38a10c7cf17d6c83014ed7/ckanext/nextgeossharvest/lib/opensearch_base.py#L141) in opensearch_base.py is passed, extending (updating) incorrectly the dataset.
-  If `update_all` is set to true, then there is a problem in the harvester update logic, and this issue should be further investigated in another issue / PR. 

So, if in the harvester configuration, the field `update_all` is set to false, in the `gather` log you are receiving the message `XXXX will not be updated.` and the UI reports 99 datasets created and 0 datasets updated, then you are experiencing the correct behavior.

**Pull request merged**
