### PR TITLE
Feature/noa groundsegment harvester

### PR DESCRIPTION
**Pull request by joaandrade**
Fixes #

### Proposed fixes:
New harvester for NOA Ground Segment

### Features:
New harvester for NOA Ground Segment Products.

This new data harvest collects products from 5 different collections. Only one harvester, continuously running, will collect all the datasets.
Data collections:
- NOA VIIRS Products (collection_id: NOA_VIIRS_PRODUCTS): Visible Infrared Imaging Radiometer Suite (VIIRS) products collected from the premises of the National Observatory of Athens (NOA).
- NOA MODIS Products (collection_id: NOA_MODIS_PRODUCTS): Moderate Resolution Imaging Spectroradiometer (MODIS) products collected from the premises of the National Observatory of Athens (NOA).
- NOA AVHRR/3 Products (collection_id: NOA_AVHRR_PRODUCTS): Advanced Very High Resolution Radiometer (AVHRR/3) products collected from the premises of the National Observatory of Athens (NOA).
- NOA AIRS Products (collection_id: NOA_AIRS_PRODUCTS): Atmospheric InfraRed Sounder (AIRS) products collected from the premises of the National Observatory of Athens (NOA).
- NOA MERSI Products (collection_id: NOA_MERSI_PRODUCTS): Medium Resolution Spectral Imager (MERSI) products collected from the premises of the National Observatory of Athens (NOA).

The harvester configuration to be used:
{
"start_date":"2019-10-01T00:00:00Z",
"end_date":"2020-10-01T23:59:00Z",
"username":"username",
"password":"password",
"page_timeout": "2"
}

- [X] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by JGulic** [comment]
@joaandrade Can you take a look at this error:
```

  File "/usr/lib/ckan/nextgeoss/src/ckanext-nextgeossharvest/ckanext/nextgeossharvest/harvesters/noa_groundsegment.py", line 314, in _get_spatial_info
    for product in products:
  File "/usr/lib/ckan/nextgeoss/src/ckanext-nextgeossharvest/ckanext/nextgeossharvest/harvesters/noa_groundsegment.py", line 173, in _build_products
    while products['next'] and page_counter < page_timeout:
KeyError: 'next'
```

**Comment by joaandrade** [comment]
Hi Jovanka,
I was not able to reproduce that error. In my local environment the harvester runs properly.

@akatsos can you please take a look to the error reported by Jovanka? Are you able to reproduce it?

Regards,
João

**Comment by joaandrade** [comment]
@JGulic I ran 5 jobs without any issues..

**Comment by joaandrade** [comment]
The problem was related to the user and pass used in the configuration.

**Comment by JGulic** [comment]
@joaandrade I can confirm that it runs now. I will merge the code.

**Pull request merged**
