### PR TITLE
Vito CGS S1 harvester

### PR DESCRIPTION
**Pull request by joaandrade**
Fixes #

### Proposed fixes:
New harvester for an external VITO project. This harvester allows to collect 3 new collections **(currently only two available)**:
 
- GCS S1 SLC L1
- CGS S1 GRD L1
- CGS S1 GRD SIGMA0 L1 **(NOT AVAILABLE YET)**

One harvester per collection must be created (currently only 2). New products are created and published daily, thus this harvester will require to be kept running.

The harvester configuration settings should be as follows, to collect all datasets in the catalog and catch all future ones:
{
"start_date":"2018-01-01",
"collection":"SLC_L1",
"username":"username",
"password":"password",
"timeout":1,
"make_private":false
}

or

{
"start_date":"2018-01-01",
"collection":"GRD_L1",
"username":"username",
"password":"password",
"timeout":1,
"make_private":false
}

### Features:

- [X] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by georgiana-b** [comment]
@joaandrade Could you also add some documentation about this harvester to the README?

**Comment by georgiana-b** [comment]
@joaandrade Just reviewed and tested this harvester. 

The only odd thing is that the query `http://www.vito-eodata.be/openSearch/findProducts.atom?collection=urn:eop:VITO:CGS_S1_SLC_L1&start=2018-01-04&end=2018-01-05` returns both the datasets from `2018-01-04` and those from `2018-01-05`, so from the second run further some of the datasets are always already harvested. 

But I guess it's more important to go the safe way and make sure we gather everything in case they change response policy in the future. So I understand why we prefer attempting to harvest datasets 2 times over risking to miss some of them.

Otherwise everything is fine except for the lack of documentation.

**Comment by joaandrade** [comment]
@davidcordeiro-deimos can you add the information to README?

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b The README.md has been updated to include the harvester information

**Pull request merged**
