### PR TITLE
Add feature to update all EBAS-NILU datasets

### PR DESCRIPTION
**Pull request by davidcordeiro-deimos**
### Features:
Regarding issue #161 :
* Add update_all to harvester configuration to allow the update of datasets from EBAS-NILU

- [X] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by JGulic** [comment]
@davidcordeiro-deimos we are going to wait for a PR for #183 in order to be able to test this PR properly

**Comment by georgiana-b** [comment]
@davidcordeiro-deimos I just tested this harvester again locally with the configuration given as example in the [README](https://github.com/NextGeoss/ckanext-nextgeossharvest#examples-of-ebas-nilu-settings) and what happens is that the harvester doesn't collect anything in the first run and it doesn't seem to move on either. On subsequent runs the Harvest URL remains:
`Harvest URL is https://ebas-oai-pmh.nilu.no/oai/provider?verb=ListRecords&metadataPrefix=iso19115&set=ebas-db&from=2017-01-01T00:00:00Z` and nothing is being harvested. Can we address that please?

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b It seems that the data provider changed their backend, and now each request takes longer (if you open that url in the browser, it takes around 40 seconds to obtain a response).

Thus, the problem is probably due to timeout configuration being to low (currently 4 seconds), try and change it to 60 seconds to be in the safe side.

**Comment by georgiana-b** [comment]
I changed it but I get the same behaviour and anyway I don't see how that would address the problem. Can you try running the  harvester starting with that date and check if it moves on?

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b I used the same configuration as described in the README.md with timeout set to 60, and it collects the datasets as expected.

If the timeout is set too low, it would mean that it would not collect any dataset, and keep stuck on the same (the behaviour that you described). Maybe the connection between your testing environment and the data provider is slower, and with 60 seconds it is still timing out.

Let me know if it solves the problem.

**Comment by georgiana-b** [comment]
@davidcordeiro-deimos Can you make sure that you are testing the harvester on this branch with the latest code?
I was running this harvester for https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/189 and it collected datasets but on this branch it doesn't collect anything even though I'm using the same configuration:

```json
{
"start_date": "2017-01-01T00:00:00Z",
"timeout": 100,
"make_private": false,
"update_all": true
}
```

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b I just re-run the harvester for branch issue161_ebas_feature_update_all and it collected 500 datasets as expected.

image

**Comment by georgiana-b** [comment]
Ok, we will test this on staging too and decide how to proceed depending on how that goes.

**Pull request merged**
