### PR TITLE
works but is unsafe

### PR DESCRIPTION
**Pull request by davv-deimos**
Added new product SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046.

Changed the logic just for this product.

Now uses the FTP module from the standard library to connect to the server. Gets all the month and year tuples from the interval between the dates passed int he config. Uses those tuples to connect to their respective directories in the FTP server. Lists all the files in each directory. Stores any file there that still hasn't been stored in CKAN (using the filename stripped ofits extension to query the CKAN).

### CODE REVIEW

**Comment by davv-deimos** [comment]
Still needs to parse each file's name to get the dates in order to correctly populate the date fields in CKAN.
right now uses the config dates to populate the fields. It should parse the first date in the file name and put it in both start and end date.

**Comment by davv-deimos** [comment]
Logs are still missing

**Comment by davv-deimos** [comment]
@JGulic  @kmbn  please ignore this two branches I created, they are just for organization purposes since me and a colleague (Nuno Costa) both use this account to commit code. By the way, can you add him to this organization? His github account is nucc-dme

**Comment by davv-deimos** [comment]
Still needs exceptions for safety.

**Comment by davv-deimos** [comment]
dates are parsed from the identifier now.

**Comment by davv-deimos** [comment]
Hi @kmbn @JGulic. I'm having this issue with Travis Cl:

```remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/NextGeoss/ckanext-harvest.git/'
Command "git clone -q https://github.com/NextGeoss/ckanext-harvest.git /home/travis/virtualenv/python2.7.14/src/ckanext-harvest" failed with error code 128 in None
```
Can you please help me with this?

**Comment by kmbn** [comment]
If you change line 65 of `ckanext-nextgeossharvest/bin/travis-build.bash` to `pip install -e git+https://github.com/ckan/ckanext-harvest.git@v1.1.0#egg=ckanext-harvest` you shouldn’t run into any problems. We’re switching from the NextGEOSS fork of ckanext-harvest to the original ckanext-harvest. The former doesn’t have the latter’s bug fixes and updates and since we’re not overriding the core of the harvester, it doesn’t make sense to use the fork in the production or testing builds.
On 3. July 2018 at 18:56:08, davv-deimos (notifications@github.com) wrote:

Hi @kmbn @JGulic. I'm having this issue with Travis Cl:

fatal: Authentication failed for 'https://github.com/NextGeoss/ckanext-harvest.git/'
Command "git clone -q https://github.com/NextGeoss/ckanext-harvest.git /home/travis/virtualenv/python2.7.14/src/ckanext-harvest" failed with error code 128 in None
Can you please help me with this?

**Comment by davv-deimos** [comment]
> We’re switching from the NextGEOSS fork of ckanext-harvest to the original ckanext-harvest. 

Nice, I always wondered why we were using a fork of that plugin.

**Comment by davv-deimos** [comment]
it seems that there are still errors

**Comment by kmbn** [comment]
@davv-deimos Sorry, I should have told you to change the line 66 too (where to find the requirements). The build was erroring because the requirements file for the fork isn't there anymore.

I just pushed an update and the build is OK now. The tests fail now, though—`ImportError: No module named gome2`. Do you have some local files that aren't committed?

**Comment by joaandrade** [comment]
@kmbn the error "no module named gome2" is probably because the GOME-2 harvester is not integrated yet but the module is being called somewhere...

**Comment by davv-deimos** [comment]
It is passing now. I think we can proceed with the integration.

**Comment by davv-deimos** [comment]
I will now make a pull request from cmems_sea_level_product to cmems so that you can integrate

**Pull request closed without merging**
