### PR TITLE
Bugfix: Harvesters CMEMS, Deimos2 and Satcen

### PR DESCRIPTION
**Pull request by davidcordeiro-deimos**
### Proposed fixes:
- Change filename pattern for CMEMS products for the collection Global Total Surface and 15m Current - Hourly (mog)
- Change resource's URL protocol for Deimos-2 products
- Fix collection name and description of a SATCEN-BETTER collection

- [ ] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [X] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Review by JGulic — CHANGES_REQUESTED** [review]
We are missing the collection information in the dataset metadata for SATCEN.
The harvester collects the data, but since there is no information about the collection in the dataset metadata the dataset is not associated with a collection.
Can you fix this as part of this PR?

**Comment by davidcordeiro-deimos** [comment]
@JGulic The issue has been solved, please proceed with the review.

**Comment by JGulic** [comment]
@davidcordeiro-deimos the harvester is still missing the collection infromation.
Collection information goes into the extra fields of the package. And for now I can't see that it's there.

**Comment by JGulic** [comment]
@davidcordeiro-deimos after another test I can see the collection information for the datasets. I will merge this, but please test it one more time on your staging environment, so we are sure that we have the information.

**Pull request merged**
