### PR TITLE
Fix GDACS harvester performance issues

### PR DESCRIPTION
**Pull request by davidcordeiro-deimos**
### Proposed fixes:
Regarding issue #196 
- Fix gdacs hanging job
    - The harvester was downloading all products, instead of checking health
- Fix second and following gdacs jobs breaking
    - The python requests session was not being closed between harvester jobs
- Remove harvest config parameters not used

### Features:

- [ ] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [X] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by georgiana-b** [comment]
@davidcordeiro-deimos  With the configuration I used in the issue and the code on this branch I'm still getting this error:


```
ng_ckan_dev   |   File "/usr/bin/paster", line 11, in <module>
ng_ckan_dev   |     load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ng_ckan_dev   |     invoke(command, command_name, options, args[1:])
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ng_ckan_dev   |     exit_code = runner.run(args)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ng_ckan_dev   |     result = self.command()
ng_ckan_dev   |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 185, in command
ng_ckan_dev   |     gather_callback(consumer, method, header, body)
ng_ckan_dev   |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 298, in gather_callback
ng_ckan_dev   |     harvest_object_ids = gather_stage(harvester, job)
ng_ckan_dev   |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 352, in gather_stage
ng_ckan_dev   |     harvest_object_ids = harvester.gather_stage(job)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/harvesters/gdacs.py", line 115, in gather_stage
ng_ckan_dev   |     start_date, end_date, harvest_job.source_id, config)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/harvesters/gdacs.py", line 132, in _gather
ng_ckan_dev   |     status_code = self._crawl_urls_http(http_url, self.provider)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/gdacs_base.py", line 185, in _crawl_urls_http
ng_ckan_dev   |     r = requests.head(url, allow_redirects=True)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 101, in head
ng_ckan_dev   |     return request('head', url, **kwargs)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
ng_ckan_dev   |     return session.request(method=method, url=url, **kwargs)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
ng_ckan_dev   |     resp = self.send(prep, **send_kwargs)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 659, in send
ng_ckan_dev   |     history = [resp for resp in gen] if allow_redirects else []
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 238, in resolve_redirects
ng_ckan_dev   |     **adapter_kwargs
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
ng_ckan_dev   |     r = adapter.send(request, **kwargs)
ng_ckan_dev   |   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
ng_ckan_dev   |     raise ConnectionError(err, request=request)
ng_ckan_dev   | requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Were you able to reproduce this?
Here is my config:

```json
{
"data_type":"signal",
"request_check":"yes",
"start_date":"1997-12-01",
"make_private":false,
"timeout":100
}
```

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b I just cleaned and rebuild the CKAN develop environment and ran the harvester with that configuration and it collected 114 datasets.

image

**Comment by georgiana-b** [comment]
It's a bit strange because sometimes I get that error and the harvester stops without collecting anything, sometimes I don't and the harvester works as expected. I'm have to investigate that further before being able to approve this.

**Comment by georgiana-b** [comment]
I've tested this on staging and I can confirm that the harvester is stopping now and it collects everything without any errors so I will approve this.

**Pull request merged**
