### PR TITLE
New SAEON harvester

### PR DESCRIPTION
**Pull request by joaandrade**
Fixes #

### Proposed fixes:
New harvester for SAEON Data from NRF/SAEON. This harvester allows to collect 1 new collection:
- Climate Systems Analysis Group (South Africa)

This harvester has an ignore list with the metadata fields that should not be indexed in SOLR.

Only one harvester is required. The harvester configuration settings should be as follows, to collect all datasets in the catalog and catch all future ones:
{
  "datasets_per_job": 100,
  "timeout": 60,
  "make_private": false,
  "source_url": "https://staging.saeon.ac.za"
}

### Features:

- [X] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by JGulic** [comment]
@joaandrade `source_url` shouldn't be in the config. Instead it should be in the URL that you are setting up in the form when creating a harvester.
That's how the harvester works in CKAN.
Since this harvester only harvests one collection and we should only create one of it's kind, you should move the `source_url` out of the config and read the value from the harvester object that you are creating.

**Comment by joaandrade** [comment]
Hi @JGulic 
For this specific harvester we put the base URL for the query in the config since the promoter told us that the URL will change in the future. They already have production datasets to be catalogued but the interface URL is still staging. The idea was to avoid updates in the code later. When they change the interface URL, we just need to update the harvester config.

**Comment by joaandrade** [comment]
@JGulic @georgiana-b when do you think it's possible to have the code review of this harvester to be merged?
Thanks in advance.
Regards,
João

**Comment by joaandrade** [comment]
@JGulic @georgiana-b any update on the code review for this harvester?
Regards,
João

**Comment by joaandrade** [comment]
@JGulic @georgiana-b we need this harvester to be merged in order to collect some datasets and present the results to the data provider.

What is your feedback?

**Comment by georgiana-b** [comment]
@joaandrade What Jovanka is saying above is that CKAN already has a mechanism that allows you to provide the source_url in this field:

image

 @jovanka I see your point but if we put it in the URL it means we will be limited to having only one harvester with this URL. Since we might get into a situation where we want to have more harvesters with this same `source_url` I think it's fine to retrieve it from the config since the effect is basically the same, just without the unique constraint.

**Comment by joaandrade** [comment]
Hi @georgiana-b I'm building a clean docker locally using this branch to try to reproduce your error. Did you use the configuration suggested in this pull request?

**Comment by georgiana-b** [comment]
Yes, using the configuration  from the README:

```
{
  "datasets_per_job": 100,
  "timeout": 60,
  "make_private": false,
  "source_url": "https://staging.saeon.ac.za"
}
```

**Comment by joaandrade** [comment]
The problem is that the timerange fields added by the SAEON team to their interface are not appearing in the responses anymore. I sent an email to Bryan (from SAEON) and put you in copy.

**Comment by georgiana-b** [comment]
@joaandrade Considering their answer, how would you like to proceed about this?

**Comment by joaandrade** [comment]
@georgiana-b as soon as they manage to add the timerange fields back in the staging environment it will be possible to finish the tests and merge the code.

**Comment by joaandrade** [comment]
@georgiana-b you can now test the harvester. The provider restarted the server and the interface seems to be working again.

**Comment by georgiana-b** [comment]
Reviewed and tested today. All good!

**Pull request merged**
