### PR TITLE
Cmems sea level product

### PR DESCRIPTION
**Pull request by davv-deimos**
This branch adds the ability to harvest sea level products to the cmems harvester.

It works by connecting to an FTP server, changing to a certain directory, listing the files there and adding them to CKAN if they were not added previously.

This logic could be applied to all the previous product types with minimum effort.

### CODE REVIEW

**Comment by kmbn** [comment]
@davv-deimos Why did you choose ftplib for the new products instead of using the existing requests-ftp code? I'm not against using ftplib, but if it's better than requests-ftp, we should just drop requests-ftp entirely instead of having two different processes for harvesting from FTP servers.

It seems like it would be easier to mock ftplib requests for testing, which would be another point in its favor, since requests-ftp and requests-mock don't seem to work together.

**Comment by davv-deimos** [comment]
@kmbn It think ftplib is a better choice since it is part of standard library and does the job required without adding an additional dependency. Before, we used requests-ftp because the logic of the harvester had to deal with HTTP and FTP together and the requests-ftp abstracted the way we connect to a FTP server so that it looked more like a HTTP one. However, as I already said in issue #36 that logic doesn't make sense. So I think we should drop requests-ftp as well as adopt the now logic of making a `ls` command in each FTP directory for all cmems products.

**Comment by kmbn** [comment]
Dropping `requests-ftp` and using `ftplib` for all the CMEMS products sounds like a good idea and I agree with all your arguments.

It makes sense to do that now so that all the products will be harvested with the same logic after we push the update. And we'll only have one harvesting method to maintain and debug in case any issues crop up.

Will you add that to the PR?

**Comment by davv-deimos** [comment]
@kmbn I don't control what enters in our sprints, @joaandrade might help you with that though

**Comment by joaandrade** [comment]
@kmbn and @davv-deimos I will create an history on our side to do the update in the CMEMS harvester.

**Comment by kmbn** [comment]
Great—thank you!

**Comment by kmbn** [comment]
The Travis build failed. Travis couldn't run the nose tests at all because of an import error (`ImportError: No module named monthdelta`). The flake8 check also failed.

Please fix the errors. I'll review the PR as soon as the Travis build passes.

(If you set up a Git pre-commit hook to run the flake8 check that's specified in the `.travis.yml` file you can catch all the flake8 errors before you push. If setting up a pre-commit hook isn't an option, you can still run flake8 manually. If you run it manually, make sure you exclude the example harvester (the command in `.travis.yml` does this). Otherwise, you'll see a lot of extra "errors" that don't need to be fixed.)

**Comment by joaandrade** [comment]
@kmbn the module monthdelta was included in the code to easily handle the date ranges and folders. How can we avoid the Travis error? Should you install the module on your side or should the module be included in the requirements.txt?

The travis logs are just related with identation or unused imports. I will fix them and commit the code again.

**Comment by kmbn** [comment]
If `monthdelta` is something you pip-installed, then it must be included in the requirements.txt. Any package or module that you import that isn't part of the Python standard library and isn't part of the source code in the repo must be included in the requirements.txt.

**Comment by joaandrade** [comment]
@kmbn the monthdelta was added and that problem looks solved. Regarding the identation and unsued variables is it necessary to update also files such as helpers.py? The only updates I did to have this new version of the harvester were on the cmems.py and cmems_base.py. Files related to other harvesters are completely outdated on this branch.

**Comment by joaandrade** [comment]
@kmbn all the flake8 errors were solved. However the following error during some tests is appearing:

ERROR: ckanext.nextgeossharvest.tests.test_cmems_harvester.test_harvester({'org': {'url': 'http://example.com/ocn', 'name': 'ocn_test_org'}, 'config': {'username': 'testuser', 'harvester_type': 'ocn', 'end_date': '2018-01-04', 'test_ftp_status': 'ok', 'make_private': False, 'timeout': 10, 'password': 'testpass', 'start_date': '2018-01-01'}}, 'ok', 30, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/parameterized/parameterized.py", line 280, in <lambda>
    nose_func = wraps(func)(lambda *args: func(*args))
  File "/home/travis/build/NextGeoss/ckanext-nextgeossharvest/ckanext/nextgeossharvest/tests/test_cmems_harvester.py", line 188, in test_harvester
    lib.run_harvest_job(job_obj, harvester)
  File "/home/travis/virtualenv/python2.7.14/src/ckanext-harvest/ckanext/harvest/tests/lib.py", line 32, in run_harvest_job
    obj_ids = queue.gather_stage(harvester, job)
  File "/home/travis/virtualenv/python2.7.14/src/ckanext-harvest/ckanext/harvest/queue.py", line 352, in gather_stage
    harvest_object_ids = harvester.gather_stage(job)
  File "/home/travis/build/NextGeoss/ckanext-nextgeossharvest/ckanext/nextgeossharvest/harvesters/cmems.py", line 124, in gather_stage
    start_date, end_date, harvest_job.source_id, config)
  File "/home/travis/build/NextGeoss/ckanext-nextgeossharvest/ckanext/nextgeossharvest/harvesters/cmems.py", line 135, in _gather
    end_date, ftp_user, ftp_passwd)
  File "/home/travis/build/NextGeoss/ckanext-nextgeossharvest/ckanext/nextgeossharvest/harvesters/cmems.py", line 223, in _get_ftp_urls
    ftp = FTP(self._get_ftp_domain(), user, passwd)
  File "/opt/python/2.7.14/lib/python2.7/ftplib.py", line 122, in __init__
    self.login(user, passwd, acct)
  File "/opt/python/2.7.14/lib/python2.7/ftplib.py", line 395, in login
    if resp[0] == '3': resp = self.sendcmd('PASS ' + passwd)
  File "/opt/python/2.7.14/lib/python2.7/ftplib.py", line 251, in sendcmd
    return self.getresp()
  File "/opt/python/2.7.14/lib/python2.7/ftplib.py", line 226, in getresp
    raise error_perm, resp
error_perm: 530 Login incorrect.

Is this related with the testuser? I did not setup this test files. Can you help me with this?

**Comment by joaandrade** [comment]
By updating the test_cmems_harvester.py file and using a correct username and password the errors are different: error_temp: 425 Security: Bad IP connecting.

I thnik the problem is not with the harvester code but somehow, the tests being performed by travis have problems connecting with the FTP. It works properly on our development environment and we are able to harvest data. I will update the test_cmems_harvester.py again to have a 'testuser' and 'testpass'.

Waiting for your feedback about the FTP connection tests. @kmbn @JGulic @michellecbox

**Comment by kmbn** [comment]
Did you ever run the tests locally? It seems like you haven't been running the tests locally while developing. You don't need to wait for Travis to run the tests. Run `nosetests --ckan --nologcapture --with-pylons=test-core.ini` in the `ckanext-nextgeossharvest` directory to run the tests.

If you checkout the last commit before the commit in this pull request, `a669ae4d481e914b616cc4b55fa0199af26f17a6`, and run the tests, you'll see that they pass. If you checkout the head of this branch and run the tests, you'll see that they fail. It has nothing to do with Travis. Someone changed something in the code between the last working commit and the head, and that change causes the tests to fail.

You can use git-bisect to find the change that causes the tests to fail.

Remember, you're changing the way the harvester works. The old tests are based on the way the harvester used to work. It's not a surprise that the tests fail now.

I suggest just deleting `test_cmems_harvester.py` entirely. We won't have any tests. It's not worth it.

Please remove the file.

It looks like there are going to be merge conflicts with `ckanext/nextgeossharvest/lib/nextgeoss_base.py` and
`ckanext/nextgeossharvest/plugin.py`. I'll fix them for you.

**Comment by joaandrade** [comment]
@kmbn withou the old tests the checks have passed. Please check the README to see all the collections included on the harvester. One harvester per collection should be created (sst, ocn, sic_south, sic_north, gpaf, slv, mog) and it is possible to harvest data since 2017-01-01 for all of them.

Hope this helps.

João

**Pull request merged**
