### PR TITLE
Ebas

### PR DESCRIPTION
**Pull request by davidcordeiro-deimos**
Fixes #

### Proposed fixes:
New harvester for EBAS NILU Data Archive collects products from the following collections:
- EBAS NILU Data Archive

The harvester configuration settings should be as follows, to collect all datasets in the catalog and catch all future ones (all configuration parameters are optional, for further information check README.md):

{
}

### Features:

- [X] includes new  features
- [ ] includes tests covering changes
- [X] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes bugfix

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by davidcordeiro-deimos** [comment]
Data source: EBAS

Description: EBAS is a database infrastructure operated by NILU – Norwegian Institute for Air Research. It’s main objective is to handle, store and disseminate atmospheric composition data generated by international and national frameworks like long-term monitoring programmes and research projects.

Logo: 
nilu-ebas-log

**Comment by georgiana-b** [comment]
@davidcordeiro-deimos Just ran the harvester locally a few times and I think it behaves a little bit peculiar.

So on the first run the restart date was "*" so basically no limits, like you suggested in the example configuration. I collected 500 datasets, some as old `1994-01-16T12:00:00.000Z`. 

On the second it automatically chose the restart date as the current date:

```
Restart date is 2019-07-26T00:09:59Z
```
and  it collected 500 datasets again. And I thought it's quite unlikely that in one day they generated as many files as from 1994 to this day. And indeed if you look at the files collected in this second run, some of them are much older than `2019-07-26T00:09:59Z`. For example:


```json
{
  "help": "http://localhost:5000/api/3/action/help_show?name=package_show",
  "success": true,
  "result": {
    "license_title": null,
    "maintainer": null,
    "relationships_as_object": [],
    "private": false,
    "maintainer_email": null,
    "num_tags": 1,
    "id": "4509f13e-6451-4021-99b4-03ab55621a56",
    "metadata_created": "2019-07-26T15:30:15.666139",
    "metadata_modified": "2019-07-26T15:30:15.666154",
    "author": null,
    "author_email": null,
    "state": "active",
    "version": null,
    "creator_user_id": "3ae7fd6a-c670-40da-9652-2c8da0378f26",
    "type": "dataset",
    "resources": [
      {
        "mimetype": "application/x-netcdf",
        "cache_url": null,
        "hash": "",
        "description": "Download the product.",
        "name": "Product Download",
        "format": "NC",
        "url": "https://thredds.nilu.no/thredds/fileServer/ebas/SK0004R.20020101000000.20181210133000.filter_1pack..aerosol.5y.1w.SK01L_f1p_hm_04.SK01L_GF_AAS.lev2.nc",
        "cache_last_updated": null,
        "package_id": "4509f13e-6451-4021-99b4-03ab55621a56",
        "created": "2019-07-26T15:30:15.684124",
        "state": "active",
        "mimetype_inner": null,
        "last_modified": null,
        "id": "dae9c424-4f0d-43f3-a440-386f3fce2544",
        "position": 0,
        "revision_id": "a603bdf7-c000-48a9-8978-b3c0afd3aed1",
        "url_type": null,
        "order": "1",
        "resource_type": "nc_product",
        "size": null
      },
      {
        "mimetype": "text/html",
        "cache_url": null,
        "hash": "",
        "description": "Standard OPeNDAP html interface for selecting data from this dataset.",
        "name": "OPeNDAP html interface",
        "format": "HTML",
        "url": "https://thredds.nilu.no/thredds/dodsC/ebas/SK0004R.20020101000000.20181210133000.filter_1pack..aerosol.5y.1w.SK01L_f1p_hm_04.SK01L_GF_AAS.lev2.nc.html",
        "cache_last_updated": null,
        "package_id": "4509f13e-6451-4021-99b4-03ab55621a56",
        "created": "2019-07-26T15:30:15.684144",
        "state": "active",
        "mimetype_inner": null,
        "last_modified": null,
        "id": "7d7ec9c6-14bf-4017-aedf-bb80df74a025",
        "position": 1,
        "revision_id": "a603bdf7-c000-48a9-8978-b3c0afd3aed1",
        "url_type": null,
        "order": "3",
        "resource_type": "manifest",
        "size": null
      }
    ],
    "num_resources": 2,
    "tags": [
      {
        "vocabulary_id": null,
        "state": "active",
        "display_name": "EBAS",
        "id": "c9f9d3a4-7f6a-4e5a-8c20-755044cdc831",
        "name": "EBAS"
      }
    ],
    "groups": [],
    "license_id": null,
    "relationships_as_subject": [],
    "organization": {
      "description": "",
      "created": "2019-07-26T10:04:46.064150",
      "title": "EBAS",
      "name": "ebas",
      "is_organization": true,
      "state": "active",
      "image_url": "",
      "revision_id": "7529bf20-aa56-4525-99ae-81b3aea72803",
      "type": "organization",
      "id": "8ce93081-9402-4e73-a484-131f332c67e4",
      "approval_status": "approved"
    },
    "name": "ebas_sk0004r_20020101000000_20181210133000",
    "isopen": false,
    "url": null,
    "notes": "Ground based in situ observations of filter_1pack at Stará Lesná (SK0004R). These measurements are gathered as a part of the following projects EMEP and they are stored in the EBAS database (http://ebas.nilu.no/). Parameters measured are: arsenic in aerosol (mass_concentration_of_arsenic_in_dry_aerosol_particles_in _air), cadmium in aerosol (mass_concentration_of_cadmium_in_dry_aerosol_particles_in _air), chromium in aerosol (mass_concentration_of_chromium_in_dry_aerosol_particles_in _air), copper in aerosol (mass_concentration_of_copper_in_dry_aerosol_particles_in _air), nickel in aerosol (mass_concentration_of_nickel_in_dry_aerosol_particles_in _air)",
    "owner_org": "8ce93081-9402-4e73-a484-131f332c67e4",
    "extras": [
      {
        "key": "Startdate",
        "value": "20020101000000"
      },
      {
        "key": "Statistics",
        "value": "arithmetic mean"
      },
      {
        "key": "OrganizationName",
        "value": "SK01L, Slovak Hydrometeorological Institute, SHMU, Dep. of Atmospheric Chemistry, Jeseniova 17, 83315, Bratislava, Slovak Republic"
      },
      {
        "key": "Matrix",
        "value": "aerosol"
      },
      {
        "key": "Station code",
        "value": "SK0004R"
      },
      {
        "key": "product_url",
        "value": "https://thredds.nilu.no/thredds/fileServer/ebas/SK0004R.20020101000000.20181210133000.filter_1pack..aerosol.5y.1w.SK01L_f1p_hm_04.SK01L_GF_AAS.lev2.nc"
      },
      {
        "key": "Set type code",
        "value": "TI"
      },
      {
        "key": "Platform code",
        "value": "SK0004S"
      },
      {
        "key": "Organization",
        "value": "SK01L, Slovak Hydrometeorological Institute, SHMU, Dep. of Atmospheric Chemistry, Jeseniova 17, , 83315, Bratislava, Slovak Republic"
      },
      {
        "key": "manifest_url",
        "value": "https://thredds.nilu.no/thredds/dodsC/ebas/SK0004R.20020101000000.20181210133000.filter_1pack..aerosol.5y.1w.SK01L_f1p_hm_04.SK01L_GF_AAS.lev2.nc.html"
      },
      {
        "key": "Data definition",
        "value": "EBAS_1.1"
      },
      {
        "key": "Originator",
        "value": "Mitosinkova, Marta, , , , , , , , , "
      },
      {
        "key": "PointOfContact",
        "value": "Marta Mitosinkova"
      },
      {
        "key": "Instrument name",
        "value": "f1p_hm_04"
      },
      {
        "key": "topicCategory",
        "value": "climatologyMeteorologyAtmosphere"
      },
      {
        "key": "Station altitude",
        "value": "808.0 m"
      },
      {
        "key": "Data level",
        "value": "2"
      },
      {
        "key": "spatial",
        "value": "{\"type\": \"Polygon\", \"coordinates\": [[[20.283333, 49.15], [20.283333, 49.15], [20.283333, 49.15], [20.283333, 49.15], [20.283333, 49.15]]]}"
      },
      {
        "key": "Method ref",
        "value": "SK01L_GF_AAS"
      },
      {
        "key": "OrganizationLink",
        "value": "ebas.nilu.no"
      },
      {
        "key": "collection_id",
        "value": "EBAS_NILU_DATA_ARCHIVE"
      },
      {
        "key": "timerange_end",
        "value": "2006-12-29T20:00:00.000Z"
      },
      {
        "key": "collection_description",
        "value": "Atmospheric composition data obtained at surface in situ stations associated to various international and national frameworks for long-term monitoring. Archived in EBAS database operated by NILU."
      },
      {
        "key": "File name",
        "value": "SK0004R.20020101000000.20181210133000.filter_1pack..aerosol.5y.1w.SK01L_f1p_hm_04.SK01L_GF_AAS.lev2.nc"
      },
      {
        "key": "collection_name",
        "value": "EBAS NILU Data Archive"
      },
      {
        "key": "Station latitude",
        "value": "49.15"
      },
      {
        "key": "Frameworks",
        "value": "EMEP"
      },
      {
        "key": "StopTime",
        "value": "2006-12-29T20:00:00.000Z"
      },
      {
        "key": "Period code",
        "value": "5y"
      },
      {
        "key": "Instrument type",
        "value": "filter_1pack"
      },
      {
        "key": "Submitter",
        "value": "Matejovicova, Jana, , , , , , , , , "
      },
      {
        "key": "MinimumAltitude",
        "value": "808.0"
      },
      {
        "key": "identifier",
        "value": "oai:ebas-oai-pmh.nilu.no:EBAS_SK0004R.20020101000000.20181210133000.filter_1pack..aerosol.5y.1w.SK01L_f1p_hm_04.SK01L_GF_AAS.lev2.nc.iso"
      },
      {
        "key": "Resolution code",
        "value": "1w"
      },
      {
        "key": "Laboratory code",
        "value": "SK01L"
      },
      {
        "key": "timerange_start",
        "value": "2002-01-05T00:00:00.000Z"
      },
      {
        "key": "Revision date",
        "value": "20181210133000"
      },
      {
        "key": "StartTime",
        "value": "2002-01-05T00:00:00.000Z"
      },
      {
        "key": "Station name",
        "value": "Stará Lesná"
      },
      {
        "key": "Timezone",
        "value": "UTC"
      },
      {
        "key": "Station longitude",
        "value": "20.283333"
      },
      {
        "key": "MaximumAltitude",
        "value": "808.0"
      },
      {
        "key": "File creation",
        "value": "20190514090602"
      },
      {
        "key": "Unit",
        "value": "ng/m3"
      },
      {
        "key": "Regime",
        "value": "IMG"
      }
    ],
    "title": "EBAS_SK0004R_20020101000000_20181210133000",
    "revision_id": "a603bdf7-c000-48a9-8978-b3c0afd3aed1"
  }
}
```

So I'm a bit confused. As far as I know setting a certain range is supposed to get only files with `timerange_start` in that range, right? The harvester seems to ignore those bounds.

**Comment by davidcordeiro-deimos** [comment]
Hello @georgiana-b Indeed the query structure of this harvester is a bit peculiar due to the following reasons:
- It allows temporal queries, however the server is not able to sort the products by any discernible pattern
- The temporal query (as well as the restart_date) refer to the ingestion date to the server not the time range of the dataset (similar to Sentinel)
- Although the query does not return the results in any sorted manner, we are able to go through all result pages with a "resumption_token"

Thus the following approach was devised:
- The first query will return all the existing products
         - The following queries will use the "resumption_token" to go through all the products found by the initial query (not **restart date**)
                  - During any product harvest, we keep saving the most recent ingestion date for future steps        
         - When the "resumption_token" is returned Null, all the products of the initial query have been harvested
- Considering that the products from the initial query have been harvested, then we are up to date with the products within the server. Thus, the following queries will be **from restart_date until NOW** in order to find any new products that have been ingested.

I hope that this explanation clarifies your doubts, any other questions do not hesitate to contact me.

**Comment by georgiana-b** [comment]
Hi @davidcordeiro-deimos! Thank you for the explanation. I understand it's difficult to work with some of the providers. That's why our work is so important. 


My main question is: if the server doesn't return results sorted temporally, how can we we be sure that the results are in fact only within the temporal constraints we are sending. For example, in the next query when you start from `restart_date until NOW`, how do you know you only get results from `restart_date` onwards? 
To me it seems that we are getting results even older that `restart_date`. So does that mean that we constantly reprocess some datasets from the past?

On another note, could you get in touch with them and ask wether we can get the data in temporally bounded chunks?

**Comment by davidcordeiro-deimos** [comment]
Hi @georgiana-b maybe my explanation was not clear, so I will try to explain with a more practical example. 

Assume that at the current time there are 1000 datasets, and that each query only returns 250 results at a time.

So, imagine that you perform the first query is `FROM * UNTIL NOW`, you will get 250 results and you harvest them. During this query you can also extract the `resumption_token` which will allow for you to cycle through the batches of 250 datasets. After collecting this token and harvesting the first 250 datasets, the job is finished.

In the second job, the query is built using the resumption_token acquired in the previous query, obtaining the next 250 datasets. Again during this job you harvest not only the datasets, but also extract the `resumption_token` for the next job.

You keep on this cycle until `resumption_token` is returned as None, which means that you have cycled through all the datasets that satisfied the initial query. Also during the harvest of each dataset you save the most recent 'ingestion_date' into 'restart_date'. **NOTE:** This is value is not used during a `resumption_token` cycle.

Now imagine that during the harvest of the initial 1000 datasets, the provider added to the server another 2000. So after finishing the first cycle, in the next job the harvester will perform a query `FROM restart_date UNTIL NOW`, which will return only the new 2000 datasets. And again you will cycle through them using the `resumption_token`.

As far as I tested there were no repetition of datasets, however if you have any example maybe it would be easier to track down the problem. **NOTE2:** The `restart_date` regards the ingestion date into the server and not the date of the dataset, i.e. the harvester only cares the date that the dataset was added into the provider server.

Regarding your last question, I am afraid that I am not understanding it.

I hope this new explanation was of any help, and if you have any other questions let me know.

**Comment by georgiana-b** [comment]
Ok, I understand. My question is if we can be sure the last `restart_date` we have is the latest one if the documents do not come in sorted in ascending order.

**Comment by davidcordeiro-deimos** [comment]
That was one of our first questions to the provider, and they said that it was possible to perform temporal queries, and thus having the keywords FROM and UNTIL. 

Regarding the variable `restart_date`, during the harvest of each dataset, the variable is updated if the ingestion date is newer than the previous.

**Comment by georgiana-b** [comment]
Ok, perfect. Thanks a lot!

**Comment by georgiana-b** [comment]
Having that said I think this is good to go further @JGulic since it does harvest what it needs to harvest.

**Pull request merged**
