### PR TITLE
Gome2 harvesting from last restart date

### PR DESCRIPTION
**Pull request by davv-deimos**
Fixes #

### Features:

- [X] includes new  features
- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes bugfix

Please [X] all the boxes above that apply

This work was requested by @joaandrade  with description below.

> The main idea of this task is to guarantee that GOME-2 harvester:
> 
> - Will be able to recover from outages automatically
> - Can start from any starting date up to present
> 
> *Important Note:* In this harvested, the functions to check if a product was already harvested or if there is no product available to harvest in some date are already implemented (_missing_or_harvested function);
> 
> So in this harvester we need to implement:
> - The code to check the date of the last product harvested (re-use code from ESA harvester);
> - Harvest automatically from the date of the last product until NOW (cronjob launching jobs)
> - Harvest from any start date until NOW *is already implemented*
> - Limit of 10 days per job (this will guarantee a maximum of 50 datasets per job)

From the description above the development team identified the following _acceptance criteria_ for this task:
1. if no GOME2 products were harvested, then the harvester job starts harvesting from the configured _start date_;
2. if GOME2 products were harvested, then the harvester job starts harvesting from the last harvested product publish date;
3. the harvester job doesn't harvest more than 10 days;
4. the harvester job doesn't try to harvest after current day;
5. the harvester job doesn't harvest after the _end date_, if it is configured.

The criteria above were verified in the following way:
1. cron job tasks to create and run a harvest job for GOME2 every minute was setup;
2. the harvest gather and fetch stage were started and their logs collected in a file;
3. jobs adding products each minute were seen in CKAN harvest jobs list;
4. datasets for both the defined _start_ and _end_ dates were found in CKAN;
5. the correct date lists, i.e. 10 dates starting at the last date of the last job, were found in the logs of  gather stage of successive jobs.

### CODE REVIEW

**Comment by davv-deimos** [comment]
The CI is failing during the `travis-build.bash` script. It seems like it's trying the install python package from [ckan harvest plugin repository](https://github.com/NextGeoss/ckanext-harvest) and its falling to find the specified tag v0.0.50. I don't know how is this supposed to be solved. @kmbn, can you take a look on that, please?

**Comment by kmbn** [comment]
@davv-deimos Yes, I'll look into the Travis issue. I think we've got several versions of the Travis build script in the various branches of this repo. I'll make sure we're using the right one in this branch.

**Comment by kmbn** [comment]
@davv-deimos I pushed an updated Travis build script that corrects the pip install errors. I also re-ran the build to remove the error status. However, the new build status is failed.

Attempting to run the tests fails because of an `IndentationError` in gome2.py. I also tried running the harvester locally, but CKAN fails to start because of the `IndentationError`.

Can you please correct the error and also verify that the commits in this PR contain the code that you've been running locally for your tests?

**Comment by kmbn** [comment]
To move things along I rebased this branch on master, which fixed the failing tests.

**Comment by kmbn** [comment]
It's impossible to configure the harvester without an `end_date` in the config. However, the description of the pull request implies that the `end_date` should be optional. Is `end_date` required or is it optional?

**Comment by kmbn** [comment]
Regarding the logic used to determine the restart date or dates: please bear in mind that DLR has gaps in their production that they have to manually resolve. It's possible that they don't produce any images for some products for a long period of time (up to a month, or even longer) while still producing images for the other products. See issue https://github.com/NextGeoss/ckanext-nextgeossharvest/issues/47.

The harvester will have to deal with those periods of outages and bulk production.

Note that it appears that there's another partial outage right now. The missing dates API reports no new products for GOME2_SO2 since February 2018. Other products like GOME_O3 have had regular image updates during the same period.

**Comment by Mvpl** [comment]
@kmbn regarding the end_date we were thinking of making it optional, although we didn't update the validate config function. If you think it is important for the end_date to be optional we will implement this on another sprint. Please let us know.

**Comment by michellecbox** [comment]
@Mvpl yes, please update the validation. Thanks!

**Comment by joaandrade** [comment]
@michellecbox, @kmbn, the end date is now optional. Please check the code on gome2_improvements branch

**Pull request merged**
